### ISSUE TITLE
mumurhash32 collision between `ufo` and `vue`

### ISSUE THREAD

**Issue by danielroe** [unjs/ohash#11]
```js
require('ohash').hash('ufo')
// '2247144487'
require('ohash').hash('vue')
// '2247144487'
```

related: https://github.com/nuxt/framework/pull/5398

**Comment by pi0** [comment]
Another collision:

```
/node_modules/vue-toastification/dist/index.css // 944007393
/node_modules/vue-toastification/dist/index.mjs // 944007393
```

**Comment by pi0** [comment]
Using SHA2 in latest 0.1.x https://github.com/unjs/ohash/pull/12

**Comment by aleclarson** [comment]
Just a shot in the dark, but it seems collisions can be easily avoided with `padEnd`?

```ts
import { murmurHash } from 'ohash'

const fixedHash = (s) => murmurHash(s.padEnd(s.length + (4 - (s.length % 4)), '\0'))

fixedHash('vue') // => 2175094470
fixedHash('ufo') // => 3195201511
```

I'm not sure if this really fixes it or not, to be honest. :)

From [this article](https://enqueuezero.com/algorithms/murmur-hash.html):
> No collisions are possible for 4-byte keys

So perhaps making sure that `remainder` is always zero fixes it? 😅 
https://github.com/unjs/ohash/blob/58a0d67ce9f3ed4b33526ea4c254a24e13fe290e/src/crypto/murmur.ts#L18

**Comment by pi0** [comment]
Really nice point @aleclarson thanks for sharing article. Do you mind to open a PR directly adding fix to murmurHash function? (Also maybe few tests)

**Comment by pi0** [comment]
Done in https://github.com/unjs/ohash/pull/83
