### ISSUE TITLE
Question: How to decrypt or unhash a hash string

### ISSUE THREAD

**Issue by therealokoro** [unjs/ohash#17]
Another beautiful library from the unjs team. I think this might be a good stand-in replacement for the popular crypto library we've used over along period of time for hashing.

But going through the README.md file, I can't really see a means to unhash a hashed string. Please can I be cleared on this.

Thank you

**Comment by danielroe** [comment]
You cannot unhash a hashed string; it is a lossy operation.

**Comment by therealokoro** [comment]
@danielroe .....thank you. Short and simmmmple 🥲
