### ISSUE TITLE
Error: Unknown object type "htmlcanvaselement"

### ISSUE THREAD

**Issue by L422Y** [unjs/ohash#21]
I use [fabricjs](https://github.com/fabricjs/fabric.js) on the server side in a handler and am getting this error all of a sudden, where it was working fine, not sure if it's because of changes in this repository or not:

```
Error: Unknown object type "htmlcanvaselement"
```

If I go in and add `htmlcanvaselement` into [object-hash.ts](https://github.com/unjs/ohash/blob/main/src/object-hash.ts) things work again:
```js
    _htmlcanvaselement(htmlcanvaselement) {
      return write("htmlcanvaselement:" + htmlcanvaselement.toString());
    },
```

Not 100% sure the correct way to handle this, I can't find anywhere to extend or override from Nuxt.

**Comment by pi0** [comment]
Hi. Sorry for late reply. Since there are many known objects like this to be supported, instead you can enable `ignoreUnknown: true` flag this way unknown classes will be working.
