### ISSUE TITLE
`hash` function returns different value in Node and Browser

### ISSUE THREAD

**Issue by farnabaz** [unjs/ohash#29]
### Environment

ohash@1.1.1

### Reproduction

It is easily reproducible by running this snippet in both environments

```ts
import { hash } from 'ohash'

console.log(hash({ where:[{ _path:"/guide/configuration" }],first:true,sort:[{ _file:1,$numeric:true }] }))
```

### Describe the bug

`ohash` behavior is different in each environment.

## Node
![image](https://user-images.githubusercontent.com/2047945/233640502-8df17881-587d-4cd2-95b7-4166b84356b0.png)

## Browser
![image](https://user-images.githubusercontent.com/2047945/233640573-be70cd76-caad-468a-8b57-ef497719e23f.png)

**Comment by pi0** [comment]
Can you please also test with `objectHash`? What is their difference?

**Comment by farnabaz** [comment]
## browser
```
object:3:string:5:first:bool:true,string:4:sort:array:1:object:2:string:8:$numeric:bool:true,string:5:_file:number:1,,string:5:where:array:1:object:1:string:5:_path:string:20:/guide/configuration,,
```

## node

```
object:3:string:5:first:boolean:true,string:4:sort:array:1:object:2:string:8:$numeric:boolean:true,string:5:_file:number:1,,string:5:where:array:1:object:1:string:5:_path:string:20:/guide/configuration,,
```

**Comment by pi0** [comment]
Thanks. This is diff:

<img width="687" alt="image" src="https://user-images.githubusercontent.com/5158436/233644258-131c845b-799c-4edb-a39b-d5331de82d72.png">

I think this new fix https://github.com/unjs/ohash/commit/7fd580f382df12d5b8af50f6bccfb1d19ead6155 is the source of regression (browser uses `bool`!)

I will try to investigate more in few hours feel free to also check why.

**Comment by pi0** [comment]
Testing in my browser (chrome), it returns `boolean`. Are you sure your browser dependency is not cached and is the latest?

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/5158436/233650453-cf510541-1622-43bf-b2ee-d8142926ec72.png">

**Comment by pi0** [comment]
I am not sure about cause but changed to `bool`. Please check with fresh lock file.
